### ISSUE TITLE
Feature request - support for nspawn files

### ISSUE THREAD

**Issue by mnussbaum** [Matt-Deacalion/vim-systemd-syntax#14]
First off just wanted to say thanks so much for this project! It's really helpful to me. I'd love if vim-systemd-syntax could handle systemd-nspawn files which have a very similar syntax to typical systemd service files. Thanks!

**Comment by Matt-Deacalion** [comment]
Hi Michael, going by the `systemd.nspawn(5)` man page, it seems detecting by the file extension `.nspawn` should do it. [What do you think](https://github.com/Matt-Deacalion/vim-systemd-syntax/pull/15/files)?

**Comment by mnussbaum** [comment]
Yeah I think that should do it!

**Comment by Matt-Deacalion** [comment]
Nice one, added.

**Comment by mnussbaum** [comment]
Thanks!
